/****************************************************************************
 * Copyright 2023 Duelance Inc. - All Rights Reserved
 * 
 * This file is part of the Duelance project.
 * 
 * Unauthorized copying, transferring or reproduction of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 ****************************************************************************/

import { useAtom } from "jotai"
import { type NextPage } from "next"
import Head from "next/head"
import { countAtom } from "@/utils/store"
import { api } from "@/utils/api"

const Home: NextPage = () => {
    const [count] = useAtom(countAtom)
    const hello = api.example.hello.useQuery({text: "world"})
    console.log(hello.data)
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
                <p>{count}</p>
            </main>
        </>
    )
}

export default Home
